// Monarch language definition for LLVM IR (converted from LLVM.tmLanguage)
// This is an initial, best-effort conversion. Some complex TextMate
// constructs (nested captures, context-specific patterns) may need
// manual tuning for perfect parity with the original grammar.

import type * as monaco from "monaco-editor";

const instructions = [
  "add",
  "alloca",
  "and",
  "ashr",
  "atomic",
  "atomicrmw",
  "bitcast",
  "br",
  "call",
  "cmpxchg",
  "eq",
  "exact",
  "extractelement",
  "extractvalue",
  "fadd",
  "fcmp",
  "fdiv",
  "fence",
  "fmul",
  "fpext",
  "fptosi",
  "fptoui",
  "fptrunc",
  "frem",
  "fsub",
  "getelementptr",
  "icmp",
  "inbounds",
  "indirectbr",
  "insertelement",
  "insertvalue",
  "inttoptr",
  "invoke",
  "landingpad",
  "load",
  "lshr",
  "mul",
  "ne",
  "nsw",
  "nuw",
  "oeq",
  "oge",
  "ogt",
  "ole",
  "olt",
  "one",
  "or",
  "ord",
  "phi",
  "ptrtoint",
  "resume",
  "ret",
  "sdiv",
  "select",
  "sext",
  "sge",
  "sgt",
  "shl",
  "shufflevector",
  "sitofp",
  "sle",
  "slt",
  "srem",
  "store",
  "sub",
  "switch",
  "to",
  "trunc",
  "udiv",
  "ueq",
  "uge",
  "uge",
  "ugt",
  "ugt",
  "uitofp",
  "ule",
  "ule",
  "ult",
  "ult",
  "une",
  "uno",
  "unreachable",
  "unwind",
  "urem",
  "va_arg",
  "xor",
  "zext",
];

const keywords = [
  "acq_rel",
  "acquire",
  "addrspace",
  "alias",
  "align",
  "alignstack",
  "alwaysinline",
  "appending",
  "argmemonly",
  "attributes",
  "asm",
  "blockaddress",
  "byval",
  "c",
  "cc",
  "ccc",
  "coldcc",
  "common",
  "constant",
  "convergent",
  "datalayout",
  "declare",
  "default",
  "define",
  "deplibs",
  "dereferenceable",
  "dereferenceable_or_null",
  "dllexport",
  "dllimport",
  "except",
  "extern_weak",
  "external",
  "false",
  "fastcc",
  "gc",
  "global",
  "hidden",
  "inalloca",
  "inaccessiblememonly",
  "inaccessiblemem_or_argmemonly",
  "inlinehint",
  "inreg",
  "internal",
  "jumptable",
  "linkonce",
  "linkonce_odr",
  "local_unnamed_addr",
  "metadata",
  "minsize",
  "module",
  "monotonic",
  "naked",
  "nest",
  "noalias",
  "nobuiltin",
  "noduplicate",
  "nonnull",
  "nocapture",
  "noimplicitfloat",
  "noinline",
  "nonlazybind",
  "noredzone",
  "noreturn",
  "norecurse",
  "nounwind",
  "null",
  "opaque",
  "optnone",
  "optsize",
  "personality",
  "prefix",
  "prologue",
  "private",
  "protected",
  "ptx_device",
  "ptx_kernel",
  "readnone",
  "readonly",
  "release",
  "returned",
  "returns_twice",
  "safestack",
  "sanitize_address",
  "sanitize_memory",
  "sanitize_thread",
  "section",
  "seq_cst",
  "sideeffect",
  "signext",
  "sret",
  "ssp",
  "sspreq",
  "sspstrong",
  "swiftself",
  "swifterror",
  "tail",
  "target",
  "thread_local",
  "triple",
  "true",
  "type",
  "undef",
  "unnamed_addr",
  "unordered",
  "uwtable",
  "volatile",
  "weak",
  "weak_odr",
  "writeonly",
  "x86_fastcallcc",
  "x86_stdcallcc",
  "zeroext",
  "zeroinitializer",
];

const types = [
  "void",
  "half",
  "float",
  "double",
  "fp128",
  "x86_fp80",
  "ppc_fp128",
  "x86mmx",
  "ptr",
  "label",
  "metadata",
];

export const monarchLanguage: monaco.languages.IMonarchLanguage = {
  defaultToken: "",
  tokenPostfix: ".llvm",

  keywords: instructions,
  keywordMods: keywords,
  types: types,

  // brackets and symbols
  brackets: [
    { open: "{", close: "}", token: "delimiter.curly" },
    { open: "[", close: "]", token: "delimiter.bracket" },
    { open: "(", close: ")", token: "delimiter.parenthesis" },
  ],

  tokenizer: {
    root: [
      // comments
      [/;.*$/, "comment.llvm"],

      // strings
      [/"([^"\\]|\\.)*"/, "string.quoted.double.llvm"],

      // floats
      [/\b\d+\.\d+(e-?\d+)?\b/, "number.float.llvm"],

      // integers (decimal / hex)
      [/\b(0x[0-9a-fA-F]+|\d+)\b/, "number.llvm"],

      // metadata: !123 or !name
      [/!\d+/, "variable.metadata.llvm"],
      [/![-a-zA-Z$._][-a-zA-Z$._0-9]*/, "variable.metadata.llvm"],

      // variables: %name or @name
      [/[%@][-a-zA-Z$._][-a-zA-Z$._0-9]*/, "variable.language.llvm"],
      [/[%]\d+/, "variable.language.llvm"],

      // types like i32, i64 or with pointers i32**, etc.
      [/\bi\d+\**\b/, "storage.type.language.llvm"],
      [
        new RegExp("\\b(" + types.join("|") + ")\\b"),
        "storage.type.language.llvm",
      ],

      // instructions (avoid matching labels like "foo:")
      [
        new RegExp("\\b(" + instructions.join("|") + ")\\b(?!\\s*:)"),
        "keyword.instruction.llvm",
      ],

      // other keywords
      [
        new RegExp("\\b(" + keywords.join("|") + ")\\b(?!\\s*:)"),
        "storage.modifier.llvm",
      ],

      // identifiers / labels
      [/[-a-zA-Z$._][-a-zA-Z$._0-9]*/, "identifier"],

      // punctuation
      [/[{}()[\],.:]/, "delimiter"],
      [/[<>!=+\-/*%&|^~]/, "operator"],
    ],
  },
};

export default monarchLanguage;
